accelerator: gpu
arch: gpt2
batch_size: 8
block_size: 1024
cache_adress: null
dataloader_backend: classic_pytorch
devices: 1
drop_last: false
epochs: 1
eval_data_dir: s3://openwebtxt/owt/val/
exp_name: gpt2-pytorch-classic-8gpus
exp_version: 0
flush_logs_every_n_steps: 25
grad_acc_steps: null
job_id: 25699
lr: 0.0006
max_minibatches_per_epoch: 10000
momentum: 0.875
num_workers: 0
optimizer: sgd
print_freq: 10
profile: true
report_dir: language/reports
run_evaluate: false
run_training: true
save_checkpoint_dir: models
save_checkpoints: false
shuffle: false
superdl_address: localhost:50051
superdl_prefetch_lookahead: 5
train_data_dir: s3://openwebtxt/owt/train/
training_seed: 1
weight_decay: 0.1
workload_type: language
