accelerator: gpu
arch: resnet18
batch_size: 128
block_size: 1024
cache_adress: null
dataloader_backend: classic_pytorch
devices: 1
drop_last: false
epochs: 3
eval_data_dir: /workspaces/super-ml-workloads/datasets/cifar-10/test/
exp_name: cifar10
exp_version: 1
flush_logs_every_n_steps: 1
grad_acc_steps: null
job_id: 290633
lr: 0.896
max_minibatches_per_epoch: 10
momentum: 0.875
num_workers: 0
optimizer: sgd
print_freq: 1
profile: true
report_dir: classification/reports
run_evaluate: false
run_training: true
save_checkpoint_dir: models
save_checkpoints: false
shuffle: false
superdl_address: localhost:50051
superdl_prefetch_lookahead: 5
train_data_dir: /workspaces/super-ml-workloads/datasets/cifar-10/train/
training_seed: 1
weight_decay: 0.0001
workload_type: vision
