name: ResNet18/Cifar-10

#dataloading configuration
s3_bucket: sdl-cifar10
s3_train_prefix: train/
s3_val_prefix: test/
num_pytorch_workers: 0

#model configuration
model_architecture: resnet18
learning_rate: 6e-4
weight_decay: 1e-1y
precision: 32 # 16, 32, 64
num_classes: 10

#training configuration
run_training: True
run_validation: True
validation_frequency: 1 #every n epochs
checkpoint_frequency: .inf #every n epochs
max_epochs: 10
max_steps: 20
batch_size: 4 #Number of samples between optimizer steps across data-parallel ranks
limit_train_batches: 10
limit_val_batches: 50