
defaults:
  # - _self_
  - dataloader: pytorch
  - dataset: imagenet
  - training: ???
  - override hydra/job_logging: disabled

num_jobs: 1
num_devices_per_job: 1
seed: 41
accelerator: 'gpu'
log_dir: mlworklaods/reports
log_interval: 50
run_training: true
run_evaluation: false
dataload_only: false


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      training: resnet18, resnet50, shufflenet, vgg16
