
defaults:
  - _self_
  - dataloader: torch_lru #shade, torch_lru, super
  - dataset: cifar10  #imagenet
  # - training: ???
  - training: resnet18
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled  

num_jobs: 1
num_devices_per_job: 1
seed: 41
accelerator: 'gpu'
log_dir: mlworklaods/logs
log_freq: 10
run_training: true
run_evaluation: false
dataload_only: false
hydra:  
  output_subdir: null  
  run:  
    dir: .
# hydra:
#   mode: MULTIRUN
#   output_subdir: null
#   sweeper:
#     params:
#       training: resnet18
#       # training: resnet50, shufflenet, vgg16

