
defaults:
  - _self_
  - dataloader: shade
  - dataset: cifar10
  - training: ???
  - override hydra/job_logging: disabled

num_jobs: 1
num_devices_per_job: 4
seed: 41
accelerator: 'gpu'
log_dir: mlworklaods/reports
log_interval: 1
run_training: true
run_evaluation: false
dataload_only: false


hydra:
  mode: RUN
  sweeper:
    params:
      training: resnet18
      #training: resnet18, resnet50, shufflenet, vgg16
      # training: resnet50, shufflenet, vgg16

