model: gpt2 #'gpt2' (124M), 'gpt2-medium' (350M), 'gpt2-large' (774m), 'gpt2-xl' (1558M)
max_epochs: 1
max_minibatches_per_epoch: null
block_size: 1024
lr: 0.0006
momentum: 0.875
grad_acc_steps: null

