model_name: pythia-14m
save_interval: 1000
global_batch_size: 64
micro_batch_size: 4
lr_warmup_steps: 2000
lr_warmup_fraction: null
epochs: null
max_tokens: 3e12  # 3 trillion
max_steps: null
max_seq_length: null
tie_embeddings: False

learning_rate: 4e-4
weight_decay: 1e-1
beta1: 0.9
beta2: 0.95
max_norm: 1.0
min_lr: 4e-5

num_pytorch_workers: 0

# /*      'pythia-14m',
#         'pythia-31m',
#         'pythia-70m',
#         'pythia-160m',
#         'pythia-410m',
#         'pythia-1b',
#         'pythia-1.4b',
#         'pythia-2.8b',