model_name: resnet18
max_epochs: 1
max_steps: null
limit_train_batches: 5 #.inf
limit_val_batches: .inf
batch_size: 64
learning_rate: 6e-4
weight_decay: 1e-1
num_pytorch_workers: 0
grad_accum_steps: 1
# validation_frequency: .inf