model_name: resnet50
max_epochs: 100000
max_steps: 500
global_batch_size: 128 #Number of samples between optimizer steps across data-parallel ranks
micro_batch_size: 128 #Number of samples per data-parallel rank
limit_train_batches: .inf
limit_val_batches: .inf
# Optimization args
learning_rate: 6e-4
weight_decay: 1e-1