#dataloading configuration
# s3_bucket: sdl-cifar10
name: cifar10_resnet18
s3_train_prefix: s3://sdl-cifar10/train/
s3_val_prefix: s3://sdl-cifar10/test/
num_pytorch_workers: 7

#model configuration
model_architecture: resnet18
learning_rate: 6e-4
weight_decay: 1e-1y
precision: 32 # 16, 32, 64
num_classes: 10

#training configuration
run_training: True
run_validation: False
validation_frequency: 1000000 #every n epochs
checkpoint_frequency: .inf #every n epochs
max_epochs: 3
max_steps: null
batch_size: 128 #Number of samples between optimizer steps across data-parallel ranks
limit_train_batches: null
limit_val_batches: null
gpu_time: 0.0166115384660046