#dataloading configuration
name: imagenet_resnet50

s3_bucket: imagenet1k-sdl
s3_train_prefix: s3://imagenet1k-sdl/train/
s3_val_prefix: s3://imagenet1k-sdl/val/
num_pytorch_workers: 0

#model configuration
model_architecture: resnet50
learning_rate: 6e-4
weight_decay: 1e-1
precision: 32 # 16, 32, 64
num_classes: 1000

#training configuration
run_training: True
run_validation: False
validation_frequency: 1000000 #every n epochs
checkpoint_frequency: .inf #every n epochs
max_epochs: 1
max_steps: 500
batch_size: 256 #Number of samples between optimizer steps across data-parallel ranks
limit_train_batches: 500
limit_val_batches: .inf